schema = 3

[mod]
  [mod."github.com/eclipse/paho.mqtt.golang"]
    version = "v1.4.2"
    hash = "sha256-VtyBNKSEc4Wz/nFV7LBJkvkIopePHjTrOVNXenNmhsU="
  [mod."github.com/go-co-op/gocron"]
    version = "v1.18.0"
    hash = "sha256-QZMjrZXkfslTI5tVIEOvzF/2sYSV8BoJBj7dJILKvRs="
  [mod."github.com/gorilla/websocket"]
    version = "v1.4.2"
    hash = "sha256-GhBLM/XTm2lFCyDvJbnCLAI2OyYXQV6W+jRPOQ1PdVY="
  [mod."github.com/robfig/cron/v3"]
    version = "v3.0.1"
    hash = "sha256-FUdqNbWYi5biQc/tjCeqzxu4iy4ot1ZvDU1M1wRf/6k="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20200425230154-ff2c4b7c35a0"
    hash = "sha256-P/Dna9bOfwiqgsD7NNIsmz96RPbjEdaG7vhGoWrHzKQ="
  [mod."golang.org/x/sync"]
    version = "v0.0.0-20210220032951-036812b2e83c"
    hash = "sha256-qyBoAsnVWZyQM7UkJ573EjijMHK0q5mVoY/o4a8Agr4="
